# -*- coding: utf-8 -*-
import base64
import io

import xlsxwriter

from odoo import api, fields, models
from odoo.exceptions import UserError, ValidationError


class ItTicket(models.Model):
    _name = "it.ticket"
    _description = "IT Ticket"
    _inherit = ["mail.thread", "mail.activity.mixin"]
    _order = "date_opened desc, id desc"
    _rec_name = "name"

    # --- Excel column: Ticket ID ---------------------------------------
    # Not required=True at field level on purpose: when Admin enables
    # auto-generation (Configuration > Settings) it is filled in create().
    # Manual mode (default, matches the normal process) is enforced by the
    # _check_name() constraint below instead.
    name = fields.Char(
        string="Ticket ID",
        copy=False,
        tracking=True,
        help="ID generated by the external ticketing tool (e.g. INC-000123), "
        "unless Admin has enabled auto-generation in Configuration > Settings.",
    )

    # --- Excel column: Type (configurable) ------------------------------
    ticket_type_id = fields.Many2one(
        "it.ticket.type", string="Type", required=True, tracking=True,
        default=lambda self: self.env.ref("it_ticket_tracker.it_ticket_type_incident", raise_if_not_found=False),
    )

    # --- Excel column: Category (configurable, multi-select) ------------
    def _default_category_ids(self):
        cat = self.env.ref("it_ticket_tracker.it_ticket_category_network", raise_if_not_found=False)
        return [(6, 0, cat.ids)] if cat else False

    category_ids = fields.Many2many("it.ticket.category", string="Category", default=_default_category_ids)

    # --- Excel column: Priority (configurable) ---------------------------
    priority_id = fields.Many2one(
        "it.ticket.priority", string="Priority", required=True, tracking=True,
        default=lambda self: self.env.ref("it_ticket_tracker.it_ticket_priority_medium", raise_if_not_found=False),
    )

    # --- Excel column: Status -> Stage (configurable, drag & drop) -------
    stage_id = fields.Many2one(
        "it.ticket.stage", string="Stage", required=True, tracking=True, group_expand="_read_group_stage_ids",
        default=lambda self: self.env.ref("it_ticket_tracker.it_ticket_stage_open", raise_if_not_found=False),
    )
    is_closed = fields.Boolean(related="stage_id.is_closed", string="Closed", store=True)

    # --- Excel column: Assigned To ---------------------------------------
    assigned_to = fields.Many2one(
        "res.users", string="Assigned To", required=True,
        default=lambda self: self.env.user, tracking=True,
    )

    # --- Excel column: Reported By (configurable directory, quick-create) --
    reported_by_id = fields.Many2one(
        "it.ticket.reporter", string="Reported By", required=True,
        help="Pick an existing requester/team, or type a new name and choose "
        "'Create ...' - it is saved for next time. Local to this module only.",
    )

    # --- Excel columns: Date Opened / Date Closed -------------------------
    date_opened = fields.Datetime(string="Date Opened", required=True, default=fields.Datetime.now)
    date_closed = fields.Datetime(string="Date Closed")

    # --- Favorite star, for quick personal filtering/tracking -------------
    favorite = fields.Boolean(string="Favorite")

    # --- Excel column (auto/grey): Resolution Time (h) ---------------------
    resolution_time = fields.Float(
        string="Resolution Time (h)",
        compute="_compute_resolution_time",
        store=True,
        digits=(16, 2),
        help="Auto-calculated: (Date Closed - Date Opened) in hours. Not editable.",
    )

    # --- Excel column (auto/grey): Week # -----------------------------------
    week_number = fields.Integer(
        string="Week #",
        compute="_compute_week_number",
        store=True,
        help="Auto-calculated ISO-8601 week number (Monday-start) from Date Opened. Not editable.",
    )

    # --- Excel column: Comments ----------------------------------------------
    comments = fields.Text(string="Comments")

    company_id = fields.Many2one("res.company", default=lambda self: self.env.company)
    color = fields.Integer(string="Kanban Color", compute="_compute_color", store=True)
    priority_badge_class = fields.Char(compute="_compute_badge_classes")
    type_badge_class = fields.Char(compute="_compute_badge_classes")
    stage_badge_class = fields.Char(compute="_compute_badge_classes")

    # Maps the Odoo 0-11 kanban color-picker index (used on the master-data
    # records) to a real Bootstrap contextual class, so Kanban badges render
    # with guaranteed, reliable colors instead of relying on undocumented
    # internal Odoo CSS class names.
    _COLOR_TO_BADGE_CLASS = {
        0: "secondary", 1: "danger", 2: "warning", 3: "warning",
        4: "info", 5: "primary", 6: "danger", 7: "primary",
        8: "info", 9: "dark", 10: "success", 11: "success",
    }

    @api.depends("priority_id.color", "ticket_type_id.color", "stage_id.color")
    def _compute_badge_classes(self):
        for rec in self:
            rec.priority_badge_class = self._COLOR_TO_BADGE_CLASS.get(rec.priority_id.color or 0, "secondary")
            rec.type_badge_class = self._COLOR_TO_BADGE_CLASS.get(rec.ticket_type_id.color or 0, "secondary")
            rec.stage_badge_class = self._COLOR_TO_BADGE_CLASS.get(rec.stage_id.color or 0, "secondary")

    @api.depends("date_opened", "date_closed")
    def _compute_resolution_time(self):
        for rec in self:
            if rec.date_opened and rec.date_closed:
                delta = rec.date_closed - rec.date_opened
                rec.resolution_time = round(delta.total_seconds() / 3600.0, 2)
            else:
                rec.resolution_time = 0.0

    @api.depends("date_opened")
    def _compute_week_number(self):
        for rec in self:
            rec.week_number = rec.date_opened.isocalendar()[1] if rec.date_opened else 0

    @api.depends("priority_id", "priority_id.color", "stage_id", "stage_id.is_closed")
    def _compute_color(self):
        for rec in self:
            rec.color = 0 if rec.stage_id.is_closed else (rec.priority_id.color or 0)

    def _read_group_stage_ids(self, stages, domain):
        """Always show every stage as a Kanban column, even empty ones -
        same behaviour as Project's Task Stages."""
        return stages.search([], order="sequence, id")

    @api.constrains("category_ids")
    def _check_category(self):
        for rec in self:
            if not rec.category_ids:
                raise ValidationError("Please select at least one Category for ticket %s." % rec.name)

    @api.constrains("name")
    def _check_name(self):
        for rec in self:
            if not rec.name:
                raise ValidationError(
                    "Ticket ID is required. Paste the ID from the external ticketing tool, "
                    "or ask an Administrator to enable auto-generation in Configuration > Settings."
                )

    @api.constrains("date_opened", "date_closed")
    def _check_dates(self):
        for rec in self:
            if rec.date_closed and rec.date_opened and rec.date_closed < rec.date_opened:
                raise ValidationError("Date Closed cannot be earlier than Date Opened (Ticket %s)." % rec.name)

    @api.constrains("stage_id", "date_closed")
    def _check_closed_requires_date(self):
        for rec in self:
            if rec.stage_id.is_closed and not rec.date_closed:
                raise ValidationError(
                    "Ticket %s is in a closing stage (%s) but has no Date Closed. "
                    "Please set the closing date." % (rec.name, rec.stage_id.name)
                )

    _sql_constraints = [
        ("name_unique", "unique(name)", "This Ticket ID already exists. Each ticket must have a unique Ticket ID."),
    ]

    @api.model_create_multi
    def create(self, vals_list):
        settings = self.env["it.ticket.settings"].sudo().get_singleton()
        for vals in vals_list:
            if settings.auto_generate_id and not vals.get("name"):
                number = self.env["ir.sequence"].sudo().next_by_code("it.ticket.sequence") or "/"
                vals["name"] = "%s%s" % (settings.id_prefix or "", number)
        return super().create(vals_list)

    # -----------------------------------------------------------------
    # Excel generation - shared by the manual "Export to Excel" button
    # and the auto-mailing feature. Reproduces the original ticket report
    # template layout (same 12 columns, same order, Resolution Time in
    # column J, Week # in column K).
    # -----------------------------------------------------------------
    def _build_xlsx_file(self):
        """Builds the report workbook in memory. Returns (filename, bytes)."""
        tickets = self
        output = io.BytesIO()
        workbook = xlsxwriter.Workbook(output, {"in_memory": True})
        sheet = workbook.add_worksheet("IT Ticket Report")

        header_fmt = workbook.add_format(
            {
                "bold": True,
                "bg_color": "#4472C4",
                "font_color": "white",
                "border": 1,
                "align": "center",
                "valign": "vcenter",
                "text_wrap": True,
            }
        )
        cell_fmt = workbook.add_format({"border": 1, "valign": "top", "text_wrap": True})
        date_fmt = workbook.add_format({"border": 1, "num_format": "yyyy-mm-dd hh:mm", "valign": "top"})
        num_fmt = workbook.add_format({"border": 1, "num_format": "0.00", "valign": "top"})
        total_label_fmt = workbook.add_format({"bold": True, "border": 1, "bg_color": "#D9E1F2"})
        total_num_fmt = workbook.add_format(
            {"bold": True, "border": 1, "bg_color": "#D9E1F2", "num_format": "0.00"}
        )

        headers = [
            "Ticket ID", "Type", "Category", "Priority", "Status", "Assigned To",
            "Reported By", "Date Opened", "Date Closed", "Resolution Time (h)",
            "Week #", "Comments",
        ]
        widths = [14, 10, 12, 10, 12, 18, 18, 18, 18, 16, 8, 45]
        for col, (title, width) in enumerate(zip(headers, widths)):
            sheet.write(0, col, title, header_fmt)
            sheet.set_column(col, col, width)
        sheet.set_row(0, 30)
        sheet.freeze_panes(1, 0)
        sheet.autofilter(0, 0, 0, len(headers) - 1)

        row = 1
        for t in tickets.sorted(lambda r: r.date_opened or fields.Datetime.now()):
            sheet.write(row, 0, t.name or "", cell_fmt)
            sheet.write(row, 1, t.ticket_type_id.name or "", cell_fmt)
            sheet.write(row, 2, ", ".join(t.category_ids.mapped("name")) or "", cell_fmt)
            sheet.write(row, 3, t.priority_id.name or "", cell_fmt)
            sheet.write(row, 4, t.stage_id.name or "", cell_fmt)
            sheet.write(row, 5, t.assigned_to.name or "", cell_fmt)
            sheet.write(row, 6, t.reported_by_id.name or "", cell_fmt)
            if t.date_opened:
                sheet.write_datetime(row, 7, t.date_opened, date_fmt)
            else:
                sheet.write(row, 7, "", cell_fmt)
            if t.date_closed:
                sheet.write_datetime(row, 8, t.date_closed, date_fmt)
            else:
                sheet.write(row, 8, "", cell_fmt)
            sheet.write_number(row, 9, t.resolution_time or 0.0, num_fmt)
            sheet.write_number(row, 10, t.week_number or 0, cell_fmt)
            sheet.write(row, 11, t.comments or "", cell_fmt)
            row += 1

        last_data_row = row  # 1-indexed Excel row of the last data line
        total_resolution = sum(t.resolution_time or 0.0 for t in tickets)
        sheet.write(row, 8, "TOTAL", total_label_fmt)
        sheet.write_formula(row, 9, "=SUM(J2:J%d)" % last_data_row, total_num_fmt, total_resolution)
        sheet.write_blank(row, 10, None, total_label_fmt)
        sheet.write_blank(row, 11, None, total_label_fmt)

        workbook.close()
        output.seek(0)
        filename = "IT_Ticket_Report_%s.xlsx" % fields.Date.context_today(self)
        return filename, output.read()

    def action_export_xlsx(self):
        if not self:
            raise UserError("Select at least one ticket to export (or apply a filter first).")
        filename, data = self._build_xlsx_file()
        attachment = self.env["ir.attachment"].create(
            {
                "name": filename,
                "type": "binary",
                "datas": base64.b64encode(data),
                "res_model": "it.ticket",
                "mimetype": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            }
        )
        return {
            "type": "ir.actions.act_url",
            "url": "/web/content/%s?download=true" % attachment.id,
            "target": "self",
        }
